package strtotime

import (
	"bufio"
	"encoding/json"
	"os"
	"reflect"
	"sort"
	"strings"
	"testing"
)

// TestDateParse_PHPParity compares DateParse output against PHP's
// date_parse output captured in testdata/date_parse_php.jsonl. The expected
// JSON is generated by testdata/date_parse_php.sh (requires PHP locally).
//
// Run: ./testdata/date_parse_php.sh > testdata/date_parse_php.jsonl
//
// Each mismatch is reported with the input, expected, and actual JSON.
func TestDateParse_PHPParity(t *testing.T) {
	path := "testdata/date_parse_php.jsonl"
	f, err := os.Open(path)
	if err != nil {
		t.Fatalf("open %s: %v", path, err)
	}
	defer f.Close()

	scanner := bufio.NewScanner(f)
	scanner.Buffer(make([]byte, 0, 64*1024), 1024*1024)
	line := 0
	for scanner.Scan() {
		line++
		raw := strings.TrimSpace(scanner.Text())
		if raw == "" {
			continue
		}
		var rec struct {
			In  string          `json:"in"`
			Out json.RawMessage `json:"out"`
		}
		if err := json.Unmarshal([]byte(raw), &rec); err != nil {
			t.Fatalf("line %d: bad jsonl: %v", line, err)
		}

		t.Run(rec.In, func(t *testing.T) {
			got := DateParse(rec.In)
			gotBytes, err := json.Marshal(got)
			if err != nil {
				t.Fatalf("marshal: %v", err)
			}

			var wantTree, gotTree any
			if err := json.Unmarshal(rec.Out, &wantTree); err != nil {
				t.Fatalf("unmarshal expected: %v", err)
			}
			if err := json.Unmarshal(gotBytes, &gotTree); err != nil {
				t.Fatalf("unmarshal got: %v", err)
			}

			diff := diffJSON("", wantTree, gotTree)
			if diff != "" {
				t.Errorf("PHP parity mismatch for %q:\n%s\n  want: %s\n  got:  %s",
					rec.In, diff, rec.Out, gotBytes)
			}
		})
	}
	if err := scanner.Err(); err != nil {
		t.Fatalf("scan: %v", err)
	}
}

// diffJSON produces a multi-line diff of two JSON trees, returning an empty
// string when they are equal.
func diffJSON(path string, want, got any) string {
	if reflect.DeepEqual(normalize(want), normalize(got)) {
		return ""
	}

	wm, wOk := want.(map[string]any)
	gm, gOk := got.(map[string]any)
	if wOk && gOk {
		var diffs []string
		seen := map[string]bool{}
		keys := []string{}
		for k := range wm {
			keys = append(keys, k)
			seen[k] = true
		}
		for k := range gm {
			if !seen[k] {
				keys = append(keys, k)
			}
		}
		sort.Strings(keys)
		for _, k := range keys {
			sub := diffJSON(joinPath(path, k), wm[k], gm[k])
			if sub != "" {
				diffs = append(diffs, sub)
			}
		}
		return strings.Join(diffs, "\n")
	}

	if !jsonValueEq(want, got) {
		return "  " + path + ": want " + format(want) + ", got " + format(got)
	}
	return ""
}

// normalize collapses empty collections ([] vs {}) — PHP emits [] for empty
// associative arrays, Go's encoding/json can produce either depending on the
// marshaler.
func normalize(v any) any {
	switch x := v.(type) {
	case []any:
		if len(x) == 0 {
			return []any{}
		}
		out := make([]any, len(x))
		for i, e := range x {
			out[i] = normalize(e)
		}
		return out
	case map[string]any:
		if len(x) == 0 {
			return []any{}
		}
		out := make(map[string]any, len(x))
		for k, e := range x {
			out[k] = normalize(e)
		}
		return out
	}
	return v
}

func jsonValueEq(a, b any) bool {
	return reflect.DeepEqual(normalize(a), normalize(b))
}

func joinPath(parent, leaf string) string {
	if parent == "" {
		return leaf
	}
	return parent + "." + leaf
}

func format(v any) string {
	b, _ := json.Marshal(v)
	return string(b)
}
